# Generated by Django 5.0.4 on 2024-04-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена товара')),
                ('count_goods', models.SmallIntegerField(default=0, verbose_name='Кол-во товара')),
                ('description', models.TextField(verbose_name='Описание товара')),
            ],
        ),
    ]
